name: smartride-backend
channels:
  - conda-forge
dependencies:
  - conda-lock
  - coverage
  - flask
  - flask-login
  - flask-migrate
  - flask-sqlalchemy
  - flask_cors
  - mamba
  - geopy
  - mypy
  - pyjwt
  - pytest
  - pytest-cov
  - pytest-rich
  - python-dotenv
  - python=3.13.2
  - pyyaml
  - requests
  - ruff
  - sqlalchemy
  - tqdm
  - typing
  - werkzeug
  - pip:
      - types-Flask-SQLAlchemy
      - types-requests
      - types-SQLAlchemy
