name: smartride-backend
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.2.25
  - cpp-expected=1.1.0
  - expat=2.6.4
  - fmt=11.1.4
  - icu=73.2
  - krb5=1.20.1
  - libarchive=3.7.7
  - libcurl=8.12.1
  - libcxx=20.1.2
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.4
  - libiconv=1.18
  - libmamba=2.0.8
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - mamba=2.0.8
  - ncurses=6.4
  - nlohmann_json=3.11.3
  - openssl=3.4.1
  - pcre2=10.42
  - pip=25.0
  - python=3.13.2
  - python_abi=3.13
  - readline=8.2
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - setuptools=75.8.0
  - simdjson=3.12.3
  - spdlog=1.15.2
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - blinker==1.9.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - coverage==7.8.0
      - dotenv==0.9.9
      - flask==3.1.0
      - flask-cors==5.0.1
      - flask-login==0.6.3
      - flask-sqlalchemy==3.1.1
      - idna==3.10
      - iniconfig==2.1.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - mypy==1.15.0
      - mypy-extensions==1.0.0
      - packaging==24.2
      - pathlib==1.0.1
      - pluggy==1.5.0
      - pyjwt==2.10.1
      - pytest==8.3.5
      - pytest-cov==6.1.1
      - python-dotenv==1.1.0
      - pyyaml==6.0.2
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - ruff==0.11.4
      - sqlalchemy==2.0.40
      - types-cryptography==3.3.23.2
      - types-pyjwt==1.7.1
      - types-requests==2.32.0.20250328
      - types-sqlalchemy==1.4.53.38
      - typing-extensions==4.13.1
      - urllib3==2.3.0
      - werkzeug==3.1.3
