name: smartride-backend
channels:
  - conda-forge
dependencies:
  - alembic
  - annotated-types
  - appdirs
  - backports
  - backports.tarfile
  - blinker
  - boltons
  - brotli-python
  - bzip2
  - ca-certificates
  - cachecontrol
  - cachecontrol-with-filecache
  - certifi
  - cffi
  - charset-normalizer
  - click
  - click-default-group
  - colorama
  - conda-lock
  - coverage
  - crashtest
  - distlib
  - dulwich
  - ensureconda
  - exceptiongroup
  - filelock
  - flask
  - flask-cors
  - flask-jwt-extended
  - flask-login
  - flask-migrate
  - flask-sqlalchemy
  - gitdb
  - gitpython
  - greenlet
  - h2
  - hpack
  - hyperframe
  - idna
  - importlib-metadata
  - importlib_resources
  - iniconfig
  - itsdangerous
  - jaraco.classes
  - jaraco.context
  - jaraco.functools
  - jinja2
  - keyring
  - libexpat
  - libffi
  - liblzma
  - libmpdec
  - libsqlite
  - libzlib
  - mako
  - markupsafe
  - more-itertools
  - msgpack-python
  - mypy
  - mypy_extensions
  - openssl
  - packaging
  - pip
  - pkginfo
  - platformdirs
  - pluggy
  - psutil
  - pycparser
  - pydantic
  - pydantic-core
  - pyjwt
  - pyproject_hooks
  - pysocks
  - pytest
  - pytest-cov
  - pytest-rich
  - python
  - python-build
  - python-dotenv
  - python-fastjsonschema
  - python-installer
  - python_abi
  - 'pywin32-ctypes # [win]'
  - pyyaml
  - requests
  - requests-toolbelt
  - ruamel.yaml
  - ruamel.yaml.clib
  - ruff
  - semver
  - setuptools
  - shellingham
  - smmap
  - sqlalchemy
  - sqlite
  - tk
  - toml
  - tomli
  - tomlkit
  - tqdm
  - trove-classifiers
  - typing-extensions
  - typing-inspection
  - typing_extensions
  - tzdata
  - 'ucrt # [win]'
  - urllib3
  - 'vc # [win]'
  - 'vc14_runtime # [win]'
  - virtualenv
  - 'vs2015_runtime # [win]'
  - werkzeug
  - 'win_inet_pton # [win]'
  - yaml
  - zipp
  - zstandard
  - pip:
      - types-Flask-SQLAlchemy
      - types-requests
      - types-SQLAlchemy
