name: smartride-backend
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.6.4
  - libffi=3.4.4
  - libmpdec=4.0.0
  - openssl=3.0.15
  - pip=25.0
  - python=3.13.2
  - python_abi=3.13
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - alembic==1.14.1
      - annotated-types==0.7.0
      - anyio==4.8.0
      - blinker==1.9.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - fastapi==0.115.10
      - flask==3.1.0
      - flask-cors==5.0.1
      - flask-jwt-extended==4.7.1
      - flask-migrate==4.1.0
      - flask-sqlalchemy==3.1.1
      - greenlet==3.1.1
      - h11==0.14.0
      - idna==3.10
      - itsdangerous==2.2.0
      - jinja2==3.1.5
      - mako==1.3.9
      - markupsafe==3.0.2
      - numpy==2.2.3
      - pandas==2.2.3
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyjwt==2.10.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - requests==2.32.3
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.38
      - starlette==0.46.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - websockets==15.0
      - werkzeug==3.1.3
