"""Add route_data to MapRoute

Revision ID: 6e7cf1db297b
Revises: bf67f2fa2393
Create Date: 2025-04-16 22:48:31.492800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7cf1db297b'
down_revision = 'bf67f2fa2393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_routes', schema=None) as batch_op:
        batch_op.drop_column('route_data')

    # ### end Alembic commands ###
