name: Run Pytest

on:
  pull_request:
    branches: ["main"]
    paths:
      - "backend/server/**"
      - "backend/tests/**"
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install test dependencies
        working-directory: backend
        run: |
          pip install pytest pytest-cov coverage

      - name: Run tests
        working-directory: backend
        run: |
          pytest --cov=server tests/
