version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend" # adjust if needed
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    # If you're using pnpm, dependabot still works because it reads package.json/lock

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
