name: ESLint

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  schedule:
    - cron: "41 21 * * 6"

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect frontend changes
        id: changes
        run: |
          git fetch origin main --no-tags --depth=1
          git diff --name-only FETCH_HEAD...HEAD > changed.txt
          if grep -q '^frontend/' changed.txt; then
            echo "has_frontend_change=true" >> $GITHUB_OUTPUT
          else
            echo "has_frontend_change=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Node.js
        if: steps.changes.outputs.has_frontend_change == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install pnpm
        if: steps.changes.outputs.has_frontend_change == 'true'
        run: npm install -g pnpm

      - name: Install dependencies
        if: steps.changes.outputs.has_frontend_change == 'true'
        working-directory: frontend
        run: pnpm install

      - name: Upload empty SARIF when skipped
        if: steps.changes.outputs.has_frontend_change == 'false'
        run: |
          cat <<EOF > empty.sarif
              {
                "version": "2.1.0",
                "runs": [
                  {
                    "tool": {
                      "driver": {
                        "name": "ESLint",
                        "informationUri": "https://eslint.org",
                        "rules": []
                      }
                    },
                    "results": []
                  }
                ]
              }
          EOF

      - name: Upload dummy analysis result
        if: steps.changes.outputs.has_frontend_change == 'false'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: empty.sarif

      - name: Run ESLint
        if: steps.changes.outputs.has_frontend_change == 'true'
        working-directory: frontend
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: |
          npx eslint . \
            --ext .js,.jsx,.ts,.tsx \
            --max-warnings=0 \
            --format @microsoft/eslint-formatter-sarif \
            --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        if: steps.changes.outputs.has_frontend_change == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: frontend/eslint-results.sarif
          wait-for-processing: true

      - name: Skip eslint
        if: steps.changes.outputs.has_frontend_change == 'false'
        run: echo "No frontend change, skipping ESLint."
