name: Run Vitest

on:
  pull_request:
    branches: ["main"]
    paths:
      - "frontend/**"
  push:
    branches: ["main"]

jobs:
  frontend-test:
    name: Frontend Vitest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: frontend

      - name: Run tests
        run: pnpm test
        working-directory: frontend
