name: Python Lint

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy==1.5.1

      - name: Ruff Check
        working-directory: backend
        run: ruff check server

      - name: Mypy Type Check
        working-directory: backend
        run: mypy --config-file=./mypy.ini server
