name: Python Lint

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect backend changes
        id: changes
        run: |
          git fetch origin main --no-tags --depth=1
          git diff --name-only FETCH_HEAD...HEAD > changed.txt
          if grep -q '^backend/' changed.txt; then
            echo "has_backend_change=true" >> $GITHUB_OUTPUT
          else
            echo "has_backend_change=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up micromamba + Conda env
        if: steps.changes.outputs.has_backend_change == 'true'
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: backend/conda_env_mac.yml
          environment-name: smartride-backend
          cache-downloads: true
          cache-environment: true
          init-shell: bash

      - name: Install dev-only Python tools
        if: steps.changes.outputs.has_backend_change == 'true'
        shell: bash -l {0}
        run: |
          micromamba run -n smartride-backend pip install ruff mypy==1.5.1 types-requests

      - name: Ruff Check
        if: steps.changes.outputs.has_backend_change == 'true'
        shell: bash -l {0}
        working-directory: backend
        run: |
          micromamba run -n smartride-backend ruff check server

      - name: Mypy Type Check
        if: steps.changes.outputs.has_backend_change == 'true'
        shell: bash -l {0}
        working-directory: backend
        run: |
          micromamba run -n smartride-backend mypy --config-file=./mypy.ini server

      - name: Skip lint check
        if: steps.changes.outputs.has_backend_change == 'false'
        run: echo "No backend change, skipping lint."
