name: Python Lint

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect backend changes
        id: changes
        run: |
          git fetch origin main --no-tags --depth=1
          git diff --name-only FETCH_HEAD...HEAD > changed.txt
          if grep -q '^backend/' changed.txt; then
            echo "has_backend_change=true" >> $GITHUB_OUTPUT
          else
            echo "has_backend_change=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Python
        if: steps.changes.outputs.has_backend_change == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        if: steps.changes.outputs.has_backend_change == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy==1.5.1 types-requests

      - name: Ruff Check
        if: steps.changes.outputs.has_backend_change == 'true'
        working-directory: backend
        run: ruff check server

      - name: Mypy Type Check
        if: steps.changes.outputs.has_backend_change == 'true'
        working-directory: backend
        run: mypy --config-file=./mypy.ini server

      - name: Skip lint check
        if: steps.changes.outputs.has_backend_change == 'false'
        run: echo "No backend change, skipping lint."
