name: Reset script parameters

on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - "backend/conda_env_mac.yml"
      - "backend/conda_env_win.yml"

jobs:
  reset-allow-easy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Reset allow-easy to 0
        run: |
          echo "0" > scripts/subscripts/run/parameters/allow-easy
      
      - name: Reset run-from-run to 0
        run: |
          echo "0" > scripts/subscripts/run/parameters/run-from-run

      - name: Commit and push change
        run: |
          git config user.name "Auto Reset Bot"
          git config user.email "reset-bot@example.com"
          git add scripts/subscripts/run/parameters/allow-easy
          git add scripts/subscripts/run/parameters/run-from-run

          if git diff --cached --quiet; then
            echo "Nothing to commit."
          else
            git commit -m "Reset script parameters due to env update"
            git push
          fi