name: Reset script parameters

on:
  pull_request:
    paths:
      - "backend/conda_env_mac.yml"
      - "backend/conda_env_win.yml"
  push:
    branches: ["main"]

jobs:
  reset-allow-easy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Reset conda-imported to 0
        run: |
          echo "0" > scripts/subscripts/env/parameters/conda-imported

      - name: Commit and push change
        run: |
          git config user.name "Auto Reset Bot"
          git config user.email "reset-bot@example.com"
          git add scripts/subscripts/env/parameters/conda-imported
          git commit -m "Reset script parameters due to env update"
          git push
