name: Reset script parameters

on:
  pull_request:
    paths:
      - "backend/conda_env_mac.yml"
      - "backend/conda_env_win.yml"
  push:
    branches: ["main"]

jobs:
  reset-conda-imported:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Reset conda-imported to 0
        run: |
          echo "0" > scripts/subscripts/env/parameters/conda-imported

      - name: Commit and push change
        run: |
          git config user.name "Auto Reset Bot"
          git config user.email "reset-bot@example.com"
          git add scripts/subscripts/env/parameters/conda-imported

          if git diff --cached --quiet; then
              echo "Nothing to commit."
              exit 0
          fi

          git commit -m "Reset script parameters due to env update"

          current_branch=$(git symbolic-ref --short HEAD || echo "")

          if [[ "$current_branch" == "main" ]]; then
            echo "On main branch, pushing..."
            git push origin main
          else
            echo "Not on a branch (detached HEAD), skipping push."
          fi
