name: Reset script parameters

on:
  push:
    branches: ["main"]

jobs:
  reset-conda-imported:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Reset conda-imported to 0
        run: |
          echo "0" > scripts/subscripts/env/parameters/conda-imported

      - name: Commit and push change
        env:
          TOKEN: ${{ secrets.BOT_PUSH_TOKEN }}
        run: |
          git config user.name "Auto Reset Bot"
          git config user.email "reset-bot@example.com"
          git add scripts/subscripts/env/parameters/conda-imported

          if git diff --cached --quiet; then
              echo "Nothing to commit."
              exit 0
          fi

          git commit -m "Reset script parameters due to env update"

          current_branch=$(git symbolic-ref --short HEAD || echo "")

          if [[ "$current_branch" == "main" ]]; then
            git remote set-url origin https://x-access-token:${TOKEN}@github.com/CS222-UIUC/team-07-project-smartride.git
            echo "On main branch, pushing..."
            git push origin main
          else
            echo "Not on a branch (detached HEAD), skipping push."
          fi
